import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, JoinColumn, CreateDateColumn } from 'typeorm';
import { Deal } from './deal.entity';

export enum PartnershipModel {
    REPEAT_CONTRACT = 'REPEAT_CONTRACT',     // Same terms, recurring
    VOLUME_DISCOUNT = 'VOLUME_DISCOUNT',     // Larger volume = better price
    SERVICE_BUNDLE = 'SERVICE_BUNDLE',       // Combined logistics/finance
    FRANCHISE = 'FRANCHISE',                 // Long-term exclusive model
    REVENUE_SHARE = 'REVENUE_SHARE'          // Ongoing % split
}

export enum PartnershipStatus {
    SUGGESTED = 'SUGGESTED',     // Auto-generated by system
    REVIEWING = 'REVIEWING',     // Parties reviewing
    ACCEPTED = 'ACCEPTED',       // Both parties agreed
    DECLINED = 'DECLINED',       // Rejected
    ACTIVE = 'ACTIVE'            // Partnership live
}

/**
 * DropPay Partnership Proposal
 * Separate from regular Proposals - these are platform-generated suggestions
 * for turning successful deals into recurring partnerships
 */
@Entity('partnership_proposals')
export class PartnershipProposal {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @ManyToOne(() => Deal, { onDelete: 'CASCADE' })
    @JoinColumn({ name: 'dealId' })
    deal: Deal;

    @Column()
    dealId: string;

    // Partnership Type
    @Column({ type: 'enum', enum: PartnershipModel })
    model: PartnershipModel;

    @CreateDateColumn()
    proposedAt: Date;

    // Qualification Metrics (why this deal qualifies)
    @Column({ type: 'jsonb' })
    qualificationMetrics: {
        dealValue: number;
        proposalAcceptanceRate: number;
        negotiationVelocity: number;
        architectSuccessRate: number;
        riskLevel: string;
    };

    // Proposed Terms
    @Column({ type: 'jsonb' })
    terms: {
        duration?: string;          // "12 months", "2 years"
        volumeCommitment?: number;  // Minimum order quantity
        priceAdjustment?: number;   // % discount for volume
        serviceInclusions?: string[]; // ['logistics', 'financing', 'insurance']
        revenueShareModel?: {
            dropPayPercentage: number;
            architectPercentage: number;
        };
    };

    // Projected Benefits
    @Column({ type: 'jsonb' })
    projectedBenefits: {
        estimatedAnnualRevenue: number;
        costSavings?: number;
        timeEfficiency?: string;
        riskReduction?: string;
    };

    // Status & Resolution
    @Column({ type: 'enum', enum: PartnershipStatus, default: PartnershipStatus.SUGGESTED })
    status: PartnershipStatus;

    @Column({ nullable: true })
    respondedAt: Date;

    @Column({ type: 'text', nullable: true })
    responseNotes: string;

    // Commission Tracking
    @Column({ type: 'float', default: 0 })
    dropPayCommission: number; // € amount DropPay earns if accepted

    @Column({ type: 'float', default: 0 })
    architectCommission: number; // € amount Architect earns

    // Metadata
    @Column({ type: 'jsonb', nullable: true })
    metadata: Record<string, any>;
}
